"""
Drive CoupledGNN (WSDM'20) on OUR cascades and dump per-cascade predictions.

This is **the closest published method to
our own formulation**, and that is why it is wired despite being the hardest of the
three: two COUPLED graph neural networks, one propagating node ACTIVATION STATE and
one propagating INFLUENCE, iterated over `K` layers to imitate the cascading effect
on the global graph. That is structurally what our structured head does with
`infected` and `frontier`, so this is the one external row where a difference is a
statement about the architecture rather than about the feature pipeline.

It is also the only entry here whose protocol withholds TIMESTAMPS entirely:
it sees the early adopter SET plus the global graph and nothing else, which is the
protocol our own `neighborhood_size` and `degree_scaled` rows sit under. Its
published numbers are MRSE / mRSE / MAPE / WroPerc rather than MSLE for that
reason: `wm_metrics.popularity_metrics` computes all four.

**Two deviations, both real, both stated on the row.** The repo's `load_data` reads
its own preprocessed pickles and needs two inputs it does not ship a derivation for:

  * `ind.<name>.features`: a 6-dimensional per-node vector. The shipped example is
    `[degree, 5 floats in [0,1]]`, i.e. a degree plus normalized centralities. We
    compute degree, PageRank, in-degree share, clustering, core number and
    betweenness-approximation, which is a defensible reading of that shape and is
    NOT the authors' exact set. This is the weak point of the row and it is why the
    entry's notes say so rather than a footnote saying "as published".
  * `<name>.emb_32`: a 32-dimensional structural embedding, described in the
    repo's own comment as "node embeddings generated by deepwalk". We generate one
    by spectral embedding of the normalized adjacency rather than by running
    DeepWalk, because adding a random-walk embedding dependency for one baseline is
    worse than a named substitution. Same dimension, same role.

Neither is the method's contribution (the coupled propagation is) but a reader
comparing this row against the paper's own Table 1 has to know that the inputs are
ours. Its published numbers are on CoupledGNN's own Weibo-D subset (23,681 users / 3,228
cascades) and are not comparable to a row produced here in any case.

**TensorFlow 1 is patched, not ported.** The registry rewrites `import tensorflow
as tf` to the `compat.v1` shim plus `disable_v2_behavior()` across the three
modules that use `tf.placeholder`, `tf.flags` and `tf.set_random_seed`. That is a
mechanical edit with no behavioural content; the alternative was a Python 3.7 venv
with `tensorflow==1.15`, which has no wheel on current platforms.

**The repo reports RMSE and keeps no per-cascade output**, so this driver builds
the model exactly as `train.py` does and reads `model.popularity_pre`: the
tensor the paper's own loss is defined on (`tf.reduce_sum(self.outputs, axis=[1,2])`)
instead of `model.error`.
"""

import json
import os
import pickle
import sys
from pathlib import Path
import numpy as np

repository_root = Path(os.environ.get("GWM_COUPLEDGNN_ROOT", os.getcwd())).resolve()
sys.path.insert(0, str(repository_root))

dataset_name = "gwm"

# The repo's own defaults, from `train.py`'s flags rather than from the paper
coupledgnn_defaults = {
    "learning_rate": 5e-4,
    "graph_learning_rate": 5e-5,
    "reg_cross_entropy": 0.5,
    "reg_l2": 1e-8,
    "n_layers": 3,
    "hidden_stategate": 20,
    "dropout": 0.0,
    "batch_size": 5,
    "normalize": True,
    "max_grad_norm": 100,
}
# Far below the repo's 100, for the same reason `casflow_driver`'s is: this has to
# finish inside a baseline timeout. Raise it before quoting a CoupledGNN number.
max_epochs = 20

# The embedding width the repo's filename hardcodes (`.emb_32`)
embedding_dim = 32


def load_instances(work_dir: Path) -> dict:
    payload = np.load(work_dir / "instances.npz", allow_pickle=True)

    return {key: payload[key] for key in payload.files}


def build_vertex_features(graph, num_nodes: int) -> list[list[float]]:
    """
    Six per-node statistics, matching the shape of the repo's shipped example.

    Its `ind.artificial1.features` rows are `[4, 0.0149, 0.0237, 0.0237, 0.4254,
    0.0068]` (an integer degree followed by five normalized floats) and the repo
    ships no derivation. These six are OURS: degree, PageRank, in-degree share,
    clustering coefficient, normalized core number, and a degree-weighted
    neighbour-degree ratio. Standard, cheap on a large graph, and stated as a
    substitution rather than passed off as the authors'.
    """
    import networkx as nx

    degrees = dict(graph.degree())
    pagerank = nx.pagerank(graph, max_iter=60, tol=1e-4)
    clustering = nx.clustering(graph)
    core = nx.core_number(graph)

    max_degree = max(max(degrees.values()), 1)
    max_core = max(max(core.values()), 1)
    total_degree = max(sum(degrees.values()), 1)

    rows = []
    for node in range(num_nodes):
        degree = degrees.get(node, 0)
        neighbours = list(graph.neighbors(node)) if node in graph else []
        neighbour_degree = (
            sum(degrees.get(other, 0) for other in neighbours) / max(degree, 1)
        )
        rows.append(
            [
                float(degree),
                float(pagerank.get(node, 0.0)),
                float(degree / total_degree),
                float(clustering.get(node, 0.0)),
                float(core.get(node, 0) / max_core),
                float(min(neighbour_degree / max_degree, 1.0)),
            ]
        )

    return rows


def build_embeddings(adjacency, num_nodes: int) -> list[list[float]]:
    """
    A 32-dimensional structural embedding, in place of the repo's DeepWalk file.

    Spectral: the leading eigenvectors of the symmetrically normalized adjacency.
    Deterministic, dependency-free, and the same ROLE the repo's `.emb_32` plays
    (a structural position per node feeding the influence GNN's input). It is not
    DeepWalk and the entry's notes say so.
    """
    import scipy.sparse as sp
    from scipy.sparse.linalg import eigsh

    degree = np.asarray(adjacency.sum(axis=1)).flatten()
    inverse = sp.diags(1.0 / np.sqrt(np.maximum(degree, 1e-12)))
    normalized = inverse @ adjacency @ inverse

    width = min(embedding_dim, max(num_nodes - 2, 1))

    try:
        _, vectors = eigsh(normalized.astype(np.float64), k=width, which="LA")
    except Exception:
        # A disconnected or tiny graph can fail to converge; a degree-only
        # embedding still gives the influence GNN a position rather than zeros
        vectors = np.zeros((num_nodes, width), dtype=np.float64)
        vectors[:, 0] = np.log1p(degree)

    embedding = np.zeros((num_nodes, embedding_dim), dtype=np.float64)
    embedding[:, : vectors.shape[1]] = vectors

    return embedding.tolist()


def write_repo_inputs(work_dir: Path, data: dict) -> tuple[dict, dict, int]:
    """
    Our cascades as the repo's own `Data/ind.<name>.*` pickles plus its `.emb_32`.

    `load_data` opens these relative to `--filepath`, and the subprocess runs in the
    repo root, so they go into `<repo>/Data/`. Returns the per-split cascade id
    order (how a prediction row maps back), the observed count per cascade, and
    `num_nodes`.
    """
    import networkx as nx
    import scipy.sparse as sp

    directory = repository_root / "Data"
    os.makedirs(directory, exist_ok=True)

    edges = np.load(work_dir / "graph.npz")["edges"]
    num_nodes = int(np.load(work_dir / "graph.npz")["num_nodes"])

    graph = nx.Graph()
    graph.add_nodes_from(range(num_nodes))
    graph.add_edges_from((int(a), int(b)) for a, b in edges)

    # The repo's `graph` object is `{src: [dsts]}` and `load_data` derives the
    # adjacency from it, so it is the graph rather than the adjacency that crosses
    neighbours = {node: sorted(graph.neighbors(node)) for node in range(num_nodes)}

    splits = {"train": ([], []), "val": ([], []), "test": ([], [])}
    order = {"train": [], "val": [], "test": []}
    observed = {}

    for index, cascade_id in enumerate(data["cascade_ids"]):
        split = str(data["splits"][index])
        if split not in splits:
            continue

        paths = json.loads(str(data["paths"][index]))
        # `x[i] = [(t, u), ...]`: the OBSERVED prefix. This protocol
        # withholds timestamps and the model reads only which nodes are in it, but
        # the tuple shape is the repo's own and `get_batch_data` unpacks it.
        adopters = [(float(when), int(nodes[-1])) for nodes, when in paths]
        # `y[i]` is a SET of every node adopting by the horizon. Only the increment
        # crosses as a label, so the set is the prefix plus that many unknown
        # nodes, which we cannot name, so the label is the prefix union whatever
        # the export recorded as having adopted. `labels` is the increment count.
        final = {int(nodes[-1]) for nodes, _ in paths}

        splits[split][0].append(adopters)
        splits[split][1].append(final)
        order[split].append(str(cascade_id))
        observed[str(cascade_id)] = len(paths)

    stem = directory / f"ind.{dataset_name}"

    for split, (xs, ys) in splits.items():
        with open(f"{stem}.{split}.x", "wb") as handle:
            pickle.dump(xs, handle)
        with open(f"{stem}.{split}.y", "wb") as handle:
            pickle.dump(ys, handle)

    with open(f"{stem}.graph", "wb") as handle:
        pickle.dump(neighbours, handle)

    with open(f"{stem}.features", "wb") as handle:
        pickle.dump(build_vertex_features(graph, num_nodes), handle)

    adjacency = nx.to_scipy_sparse_array(
        graph, nodelist=list(range(num_nodes)), format="csr", dtype=float
    )
    embedding = build_embeddings(sp.csr_matrix(adjacency), num_nodes)

    # `load_embeddings` reads a word2vec-style text file: a `n dim` header, then
    # one `id v1 v2 ...` line per node
    with open(directory / f"{dataset_name}.emb_32", "w", encoding="utf-8") as handle:
        handle.write(f"{num_nodes} {embedding_dim}\n")
        for node, vector in enumerate(embedding):
            handle.write(f"{node} " + " ".join(f"{value:.6f}" for value in vector) + "\n")

    return order, observed, num_nodes


if __name__ == "__main__":
    work_dir = Path(sys.argv[1])
    import tensorflow as tf
    from models import CoupledGNN
    from utils import construct_feed_dict, load_data, preprocess_adj

    data = load_instances(work_dir)
    order, observed, num_nodes = write_repo_inputs(work_dir, data)

    print(
        f"[coupledgnn_driver] {len(data['cascade_ids'])} cascades over {num_nodes} "
        f"nodes; train {len(order['train'])} / val {len(order['val'])} / "
        f"test {len(order['test'])}"
    )

    adjacency, train_x, train_y, val_x, val_y, test_x, test_y, features = load_data(
        dataset_name, f"{repository_root}{os.sep}"
    )
    support = preprocess_adj(adjacency, coupledgnn_defaults["normalize"])
    _, initial_values, _ = support

    placeholders = {
        "support_indices": tf.placeholder(tf.int64, shape=(None, 2)),
        "Xs": tf.placeholder(tf.float32, shape=(None, adjacency.shape[0], 1)),
        "y": tf.placeholder(tf.float32, shape=(None, adjacency.shape[0])),
        "dropout": tf.placeholder_with_default(0.0, shape=()),
    }

    # `CoupledGNN.__init__` reads its hyperparameters off a flags-like object, so a
    # namespace with the same attribute names stands in for the absl FLAGS the CLI
    # would have built
    from types import SimpleNamespace

    flags = SimpleNamespace(**coupledgnn_defaults)
    model = CoupledGNN(
        flags, initial_values, placeholders, features, n_nodes=adjacency.shape[0]
    )

    session = tf.Session()
    session.run(tf.global_variables_initializer())
    feed = construct_feed_dict(support, placeholders)

    def batches(xs, ys):
        size = coupledgnn_defaults["batch_size"]
        for start in range(0, len(xs), size):
            chunk_x, chunk_y = [], []
            for index in range(start, min(start + size, len(xs))):
                dense_x = np.zeros((adjacency.shape[0], 1))
                dense_y = np.zeros(adjacency.shape[0])
                for _, node in xs[index]:
                    dense_x[int(node)] = 1.0
                for node in ys[index]:
                    dense_y[int(node)] = 1.0
                chunk_x.append(dense_x)
                chunk_y.append(dense_y)

            yield start, chunk_x, chunk_y

    for epoch in range(max_epochs):
        losses = []
        for _, chunk_x, chunk_y in batches(train_x, train_y):
            feed.update(
                {
                    placeholders["Xs"]: chunk_x,
                    placeholders["y"]: chunk_y,
                    placeholders["dropout"]: coupledgnn_defaults["dropout"],
                }
            )
            outputs = session.run([model.opt_op, model.loss], feed_dict=feed)
            losses.append(outputs[1])

        print(f"[coupledgnn_driver] epoch {epoch + 1}/{max_epochs} loss {np.mean(losses):.5f}")

    predictions = {}

    # BOTH pools are predicted: the arm makes two passes (selection, then held-out)
    # and a repo invoked once has to cover both
    for split, (xs, ys) in (
        ("train", (train_x, train_y)),
        ("val", (val_x, val_y)),
        ("test", (test_x, test_y)),
    ):
        if not order[split]:
            continue

        for start, chunk_x, chunk_y in batches(xs, ys):
            feed.update(
                {
                    placeholders["Xs"]: chunk_x,
                    placeholders["y"]: chunk_y,
                    placeholders["dropout"]: 0.0,
                }
            )
            # `popularity_pre` is the tensor the paper's own loss is defined on;
            # `model.error` is an RMSE with no per-cascade output
            values = np.atleast_1d(
                np.asarray(session.run(model.popularity_pre, feed_dict=feed))
            )

            for offset, value in enumerate(values):
                row = start + offset
                if row >= len(order[split]):
                    break

                cascade_id = order[split][row]
                predictions[cascade_id] = max(
                    float(value), float(observed.get(cascade_id, 0))
                )

    (work_dir / "predictions.json").write_text(
        json.dumps({"popularities": predictions})
    )
    print(f"[coupledgnn_driver] wrote {len(predictions)} predictions")
